USE MARKET.NATIONALMARKET;
USE ROLE SYSADMIN;
USE WAREHOUSE SYS_WH;
CREATE
OR REPLACE FILE FORMAT my_csv_format TYPE = 'CSV' FIELD_DELIMITER = '|' SKIP_HEADER = 1 NULL_IF = ('NULL', 'null') COMPRESSION = 'AUTO' RECORD_DELIMITER = '\n' FIELD_OPTIONALLY_ENCLOSED_BY = NONE;
