USE MARKET.NATIONALMARKET;
USE ROLE SYSADMIN;
USE WAREHOUSE SYS_WH;
CREATE STAGE STAGE_PRODUCTS;
CREATE STAGE STAGE_HISTORIC_PRODUCTS;
CREATE STAGE STAGE_STORES;
CREATE STAGE STAGE_HISTORIC_STORES;
CREATE STAGE STAGE_SALES;
CREATE STAGE STAGE_HISTORIC_SALES;
