CREATE DATABASE MARKET;
CREATE SCHEMA NATIONALMARKET;
USE MARKET.NATIONALMARKET;
CREATE WAREHOUSE SYS_WH WITH WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 300 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
USE ROLE SYSADMIN;
CREATE WAREHOUSE SLM_WH WITH WAREHOUSE_SIZE = 'SMALL' AUTO_SUSPEND = 300 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;
USE ROLE SYSADMIN;
USE WAREHOUSE SYS_WH;
CREATE
OR REPLACE TABLE MARKET.NATIONALMARKET.PRODUCT (
    ID_PRODUCT NUMBER(38, 0) PRIMARY KEY autoincrement start 1 increment 1 noorder,
    PRODUCT_NAME VARCHAR(16777216),
    BRAND VARCHAR(16777216),
    HEIGHT FLOAT,
    WIDTH FLOAT,
    DEPTH FLOAT,
    WEIGHT FLOAT,
    PACKAGE_TYPE VARCHAR(16777216),
    PRICE NUMBER(38, 0)
);
CREATE
OR REPLACE TABLE MARKET.NATIONALMARKET.PRODUCT_TEMP (
    ID_PRODUCT NUMBER(38, 0),
    PRODUCT_NAME VARCHAR(16777216),
    BRAND VARCHAR(16777216),
    HEIGHT FLOAT,
    WIDTH FLOAT,
    DEPTH FLOAT,
    WEIGHT FLOAT,
    PACKAGE_TYPE VARCHAR(16777216),
    PRICE NUMBER(38, 0)
);
create
or replace TABLE MARKET.NATIONALMARKET.SALES (
    ID_PRODUCT INT,
    STORE_NUMBER INT,
    AMOUNT NUMBER(38, 0),
    UNITS_SOLD NUMBER(38, 0),
    MONTH_SALE DATE
);
CREATE
OR REPLACE TABLE MARKET.NATIONALMARKET.SALES_TEMP (
    ID_PRODUCT INT,
    STORE_NUMBER INT,
    AMOUNT NUMBER(38, 0),
    UNITS_SOLD NUMBER(38, 0),
    MONTH_SALE DATE
);
create
or replace TABLE MARKET.NATIONALMARKET.STORE (
    STORE_NAME VARCHAR(16777216),
    STORE_NUMBER INT PRIMARY KEY autoincrement start 1 increment 1 noorder,
    STORE_DIRECTION VARCHAR(16777216),
    STATUS VARCHAR(16777216)
);
CREATE
OR REPLACE TABLE MARKET.NATIONALMARKET.STORE_TEMP (
    STORE_NAME VARCHAR(16777216),
    STORE_NUMBER INT PRIMARY KEY autoincrement start 1 increment 1 noorder,
    STORE_DIRECTION VARCHAR(16777216),
    STATUS VARCHAR(16777216)
);
