USE MARKET.NATIONALMARKET;
USE ROLE SYSADMIN;
USE WAREHOUSE SYS_WH;
CREATE
OR REPLACE TASK MARKET.NATIONALMARKET.BULK_LOAD_PRODUCTS WAREHOUSE = 'SYS_WH' SCHEDULE = 'USING CRON 0 0 1 * * UTC' COMMENT = 'Task to load product data from STAGE_PRODUCTS and archive to STAGE_HISTORIC_PRODUCTS with month suffix' AS BEGIN CALL MARKET.NATIONALMARKET.LOAD_PRODUCTS_FROM_STAGE();
CALL MARKET.NATIONALMARKET.COPY_PRODUCTS();
CALL MARKET.NATIONALMARKET.REMOVE_FILE_PRODUCTS();
END;
CREATE
OR REPLACE TASK MARKET.NATIONALMARKET.BULK_LOAD_STORES WAREHOUSE = 'SYS_WH' SCHEDULE = 'USING CRON 0 0 1 * * UTC' COMMENT = 'Task to load store data from STAGE_STORES and archive to STAGE_HISTORIC_STORES with month suffix' AS BEGIN CALL MARKET.NATIONALMARKET.LOAD_STORES_FROM_STAGE();
CALL MARKET.NATIONALMARKET.COPY_STORES();
CALL MARKET.NATIONALMARKET.REMOVE_FILE_STORES();
END;
create
or replace task MARKET.NATIONALMARKET.BULK_LOAD_SALES warehouse = 'SYS_WH' schedule = 'USING CRON * */3 * * * UTC' as BEGIN CALL LOAD_SALES_FROM_STAGE();
CALL COPY_SALES();
CALL REMOVE_FILE_SALES();
END;
